// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: analytics.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyticsService_GetVideos_FullMethodName         = "/analytics.AnalyticsService/GetVideos"
	AnalyticsService_GetTopChannels_FullMethodName    = "/analytics.AnalyticsService/GetTopChannels"
	AnalyticsService_GetVideosCount_FullMethodName    = "/analytics.AnalyticsService/GetVideosCount"
	AnalyticsService_GetTrackedRegions_FullMethodName = "/analytics.AnalyticsService/GetTrackedRegions"
	AnalyticsService_GetVideoTrend_FullMethodName     = "/analytics.AnalyticsService/GetVideoTrend"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsServiceClient interface {
	GetVideos(ctx context.Context, in *GetVideosRequest, opts ...grpc.CallOption) (*GetVideosResponse, error)
	GetTopChannels(ctx context.Context, in *GetTopChannelsRequest, opts ...grpc.CallOption) (*GetTopChannelsResponse, error)
	GetVideosCount(ctx context.Context, in *GetVideosCountRequest, opts ...grpc.CallOption) (*GetVideosCountResponse, error)
	GetTrackedRegions(ctx context.Context, in *GetTrackedRegionsRequest, opts ...grpc.CallOption) (*GetTrackedRegionsResponse, error)
	GetVideoTrend(ctx context.Context, in *GetVideoTrendRequest, opts ...grpc.CallOption) (*GetVideoTrendResponse, error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) GetVideos(ctx context.Context, in *GetVideosRequest, opts ...grpc.CallOption) (*GetVideosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVideosResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetVideos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetTopChannels(ctx context.Context, in *GetTopChannelsRequest, opts ...grpc.CallOption) (*GetTopChannelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopChannelsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetTopChannels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetVideosCount(ctx context.Context, in *GetVideosCountRequest, opts ...grpc.CallOption) (*GetVideosCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVideosCountResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetVideosCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetTrackedRegions(ctx context.Context, in *GetTrackedRegionsRequest, opts ...grpc.CallOption) (*GetTrackedRegionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrackedRegionsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetTrackedRegions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetVideoTrend(ctx context.Context, in *GetVideoTrendRequest, opts ...grpc.CallOption) (*GetVideoTrendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVideoTrendResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetVideoTrend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations must embed UnimplementedAnalyticsServiceServer
// for forward compatibility.
type AnalyticsServiceServer interface {
	GetVideos(context.Context, *GetVideosRequest) (*GetVideosResponse, error)
	GetTopChannels(context.Context, *GetTopChannelsRequest) (*GetTopChannelsResponse, error)
	GetVideosCount(context.Context, *GetVideosCountRequest) (*GetVideosCountResponse, error)
	GetTrackedRegions(context.Context, *GetTrackedRegionsRequest) (*GetTrackedRegionsResponse, error)
	GetVideoTrend(context.Context, *GetVideoTrendRequest) (*GetVideoTrendResponse, error)
	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsServiceServer struct{}

func (UnimplementedAnalyticsServiceServer) GetVideos(context.Context, *GetVideosRequest) (*GetVideosResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVideos not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetTopChannels(context.Context, *GetTopChannelsRequest) (*GetTopChannelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopChannels not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetVideosCount(context.Context, *GetVideosCountRequest) (*GetVideosCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVideosCount not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetTrackedRegions(context.Context, *GetTrackedRegionsRequest) (*GetTrackedRegionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrackedRegions not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetVideoTrend(context.Context, *GetVideoTrendRequest) (*GetVideoTrendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVideoTrend not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {}
func (UnimplementedAnalyticsServiceServer) testEmbeddedByValue()                          {}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	// If the following call panics, it indicates UnimplementedAnalyticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_GetVideos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVideosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetVideos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetVideos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetVideos(ctx, req.(*GetVideosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetTopChannels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopChannelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetTopChannels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetTopChannels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetTopChannels(ctx, req.(*GetTopChannelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetVideosCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVideosCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetVideosCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetVideosCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetVideosCount(ctx, req.(*GetVideosCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetTrackedRegions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrackedRegionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetTrackedRegions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetTrackedRegions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetTrackedRegions(ctx, req.(*GetTrackedRegionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetVideoTrend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVideoTrendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetVideoTrend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetVideoTrend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetVideoTrend(ctx, req.(*GetVideoTrendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytics.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVideos",
			Handler:    _AnalyticsService_GetVideos_Handler,
		},
		{
			MethodName: "GetTopChannels",
			Handler:    _AnalyticsService_GetTopChannels_Handler,
		},
		{
			MethodName: "GetVideosCount",
			Handler:    _AnalyticsService_GetVideosCount_Handler,
		},
		{
			MethodName: "GetTrackedRegions",
			Handler:    _AnalyticsService_GetTrackedRegions_Handler,
		},
		{
			MethodName: "GetVideoTrend",
			Handler:    _AnalyticsService_GetVideoTrend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analytics.proto",
}
