// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: analytics.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SortBy int32

const (
	SortBy_SORT_BY_UNSPECIFIED SortBy = 0
	SortBy_APPEAR_COUNT        SortBy = 1
	SortBy_VIEW_COUNT          SortBy = 2
)

// Enum value maps for SortBy.
var (
	SortBy_name = map[int32]string{
		0: "SORT_BY_UNSPECIFIED",
		1: "APPEAR_COUNT",
		2: "VIEW_COUNT",
	}
	SortBy_value = map[string]int32{
		"SORT_BY_UNSPECIFIED": 0,
		"APPEAR_COUNT":        1,
		"VIEW_COUNT":          2,
	}
)

func (x SortBy) Enum() *SortBy {
	p := new(SortBy)
	*p = x
	return p
}

func (x SortBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortBy) Descriptor() protoreflect.EnumDescriptor {
	return file_analytics_proto_enumTypes[0].Descriptor()
}

func (SortBy) Type() protoreflect.EnumType {
	return &file_analytics_proto_enumTypes[0]
}

func (x SortBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortBy.Descriptor instead.
func (SortBy) EnumDescriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{0}
}

type GetVideosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	CategoryId    int32                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	FetchedAfter  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=fetched_after,json=fetchedAfter,proto3" json:"fetched_after,omitempty"`
	FetchedBefore *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=fetched_before,json=fetchedBefore,proto3" json:"fetched_before,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideosRequest) Reset() {
	*x = GetVideosRequest{}
	mi := &file_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideosRequest) ProtoMessage() {}

func (x *GetVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideosRequest.ProtoReflect.Descriptor instead.
func (*GetVideosRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *GetVideosRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GetVideosRequest) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *GetVideosRequest) GetFetchedAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.FetchedAfter
	}
	return nil
}

func (x *GetVideosRequest) GetFetchedBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.FetchedBefore
	}
	return nil
}

func (x *GetVideosRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetVideosRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetVideosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*Video               `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideosResponse) Reset() {
	*x = GetVideosResponse{}
	mi := &file_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideosResponse) ProtoMessage() {}

func (x *GetVideosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideosResponse.ProtoReflect.Descriptor instead.
func (*GetVideosResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *GetVideosResponse) GetVideos() []*Video {
	if x != nil {
		return x.Videos
	}
	return nil
}

type Video struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	FetchedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=fetched_at,json=fetchedAt,proto3" json:"fetched_at,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	ChannelId     string                 `protobuf:"bytes,6,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ChannelTitle  string                 `protobuf:"bytes,7,opt,name=channel_title,json=channelTitle,proto3" json:"channel_title,omitempty"`
	PublishedAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	CategoryId    int32                  `protobuf:"varint,9,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	ViewCount     int64                  `protobuf:"varint,10,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	LikeCount     int64                  `protobuf:"varint,11,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	CommentCount  int64                  `protobuf:"varint,12,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Video) Reset() {
	*x = Video{}
	mi := &file_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *Video) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *Video) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Video) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Video) GetFetchedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FetchedAt
	}
	return nil
}

func (x *Video) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Video) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *Video) GetChannelTitle() string {
	if x != nil {
		return x.ChannelTitle
	}
	return ""
}

func (x *Video) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *Video) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Video) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *Video) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Video) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

type GetTopChannelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	SortBy        SortBy                 `protobuf:"varint,3,opt,name=sort_by,json=sortBy,proto3,enum=analytics.SortBy" json:"sort_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopChannelsRequest) Reset() {
	*x = GetTopChannelsRequest{}
	mi := &file_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopChannelsRequest) ProtoMessage() {}

func (x *GetTopChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopChannelsRequest.ProtoReflect.Descriptor instead.
func (*GetTopChannelsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *GetTopChannelsRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GetTopChannelsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTopChannelsRequest) GetSortBy() SortBy {
	if x != nil {
		return x.SortBy
	}
	return SortBy_SORT_BY_UNSPECIFIED
}

type GetTopChannelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      []*Channel             `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopChannelsResponse) Reset() {
	*x = GetTopChannelsResponse{}
	mi := &file_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopChannelsResponse) ProtoMessage() {}

func (x *GetTopChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopChannelsResponse.ProtoReflect.Descriptor instead.
func (*GetTopChannelsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *GetTopChannelsResponse) GetChannels() []*Channel {
	if x != nil {
		return x.Channels
	}
	return nil
}

type Channel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ChannelTitle  string                 `protobuf:"bytes,2,opt,name=channel_title,json=channelTitle,proto3" json:"channel_title,omitempty"`
	AppearCount   int64                  `protobuf:"varint,3,opt,name=appear_count,json=appearCount,proto3" json:"appear_count,omitempty"`
	ViewCount     int64                  `protobuf:"varint,4,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Channel) Reset() {
	*x = Channel{}
	mi := &file_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Channel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Channel) ProtoMessage() {}

func (x *Channel) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Channel.ProtoReflect.Descriptor instead.
func (*Channel) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *Channel) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *Channel) GetChannelTitle() string {
	if x != nil {
		return x.ChannelTitle
	}
	return ""
}

func (x *Channel) GetAppearCount() int64 {
	if x != nil {
		return x.AppearCount
	}
	return 0
}

func (x *Channel) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

type GetVideosCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideosCountRequest) Reset() {
	*x = GetVideosCountRequest{}
	mi := &file_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideosCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideosCountRequest) ProtoMessage() {}

func (x *GetVideosCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideosCountRequest.ProtoReflect.Descriptor instead.
func (*GetVideosCountRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{6}
}

type GetVideosCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideosCountResponse) Reset() {
	*x = GetVideosCountResponse{}
	mi := &file_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideosCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideosCountResponse) ProtoMessage() {}

func (x *GetVideosCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideosCountResponse.ProtoReflect.Descriptor instead.
func (*GetVideosCountResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *GetVideosCountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetTrackedRegionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrackedRegionsRequest) Reset() {
	*x = GetTrackedRegionsRequest{}
	mi := &file_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrackedRegionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackedRegionsRequest) ProtoMessage() {}

func (x *GetTrackedRegionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackedRegionsRequest.ProtoReflect.Descriptor instead.
func (*GetTrackedRegionsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{8}
}

type GetTrackedRegionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Regions       []string               `protobuf:"bytes,2,rep,name=regions,proto3" json:"regions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrackedRegionsResponse) Reset() {
	*x = GetTrackedRegionsResponse{}
	mi := &file_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrackedRegionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackedRegionsResponse) ProtoMessage() {}

func (x *GetTrackedRegionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackedRegionsResponse.ProtoReflect.Descriptor instead.
func (*GetTrackedRegionsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{9}
}

func (x *GetTrackedRegionsResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetTrackedRegionsResponse) GetRegions() []string {
	if x != nil {
		return x.Regions
	}
	return nil
}

type GetVideoTrendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoTrendRequest) Reset() {
	*x = GetVideoTrendRequest{}
	mi := &file_analytics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoTrendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoTrendRequest) ProtoMessage() {}

func (x *GetVideoTrendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoTrendRequest.ProtoReflect.Descriptor instead.
func (*GetVideoTrendRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{10}
}

func (x *GetVideoTrendRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type GetVideoTrendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*TrendPoint          `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoTrendResponse) Reset() {
	*x = GetVideoTrendResponse{}
	mi := &file_analytics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoTrendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoTrendResponse) ProtoMessage() {}

func (x *GetVideoTrendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoTrendResponse.ProtoReflect.Descriptor instead.
func (*GetVideoTrendResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{11}
}

func (x *GetVideoTrendResponse) GetPoints() []*TrendPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type TrendPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FetchedAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=fetched_at,json=fetchedAt,proto3" json:"fetched_at,omitempty"`
	ViewCount     int64                  `protobuf:"varint,2,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	LikeCount     int64                  `protobuf:"varint,3,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	CommentCount  int64                  `protobuf:"varint,4,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendPoint) Reset() {
	*x = TrendPoint{}
	mi := &file_analytics_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendPoint) ProtoMessage() {}

func (x *TrendPoint) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendPoint.ProtoReflect.Descriptor instead.
func (*TrendPoint) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{12}
}

func (x *TrendPoint) GetFetchedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FetchedAt
	}
	return nil
}

func (x *TrendPoint) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *TrendPoint) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *TrendPoint) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

var File_analytics_proto protoreflect.FileDescriptor

const file_analytics_proto_rawDesc = "" +
	"\n" +
	"\x0fanalytics.proto\x12\tanalytics\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfd\x01\n" +
	"\x10GetVideosRequest\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x05R\n" +
	"categoryId\x12?\n" +
	"\rfetched_after\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ffetchedAfter\x12A\n" +
	"\x0efetched_before\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rfetchedBefore\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offset\"=\n" +
	"\x11GetVideosResponse\x12(\n" +
	"\x06videos\x18\x01 \x03(\v2\x10.analytics.VideoR\x06videos\"\xa9\x03\n" +
	"\x05Video\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x129\n" +
	"\n" +
	"fetched_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tfetchedAt\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x06 \x01(\tR\tchannelId\x12#\n" +
	"\rchannel_title\x18\a \x01(\tR\fchannelTitle\x12=\n" +
	"\fpublished_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x12\x1f\n" +
	"\vcategory_id\x18\t \x01(\x05R\n" +
	"categoryId\x12\x1d\n" +
	"\n" +
	"view_count\x18\n" +
	" \x01(\x03R\tviewCount\x12\x1d\n" +
	"\n" +
	"like_count\x18\v \x01(\x03R\tlikeCount\x12#\n" +
	"\rcomment_count\x18\f \x01(\x03R\fcommentCount\"q\n" +
	"\x15GetTopChannelsRequest\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12*\n" +
	"\asort_by\x18\x03 \x01(\x0e2\x11.analytics.SortByR\x06sortBy\"H\n" +
	"\x16GetTopChannelsResponse\x12.\n" +
	"\bchannels\x18\x01 \x03(\v2\x12.analytics.ChannelR\bchannels\"\x8f\x01\n" +
	"\aChannel\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12#\n" +
	"\rchannel_title\x18\x02 \x01(\tR\fchannelTitle\x12!\n" +
	"\fappear_count\x18\x03 \x01(\x03R\vappearCount\x12\x1d\n" +
	"\n" +
	"view_count\x18\x04 \x01(\x03R\tviewCount\"\x17\n" +
	"\x15GetVideosCountRequest\".\n" +
	"\x16GetVideosCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"\x1a\n" +
	"\x18GetTrackedRegionsRequest\"K\n" +
	"\x19GetTrackedRegionsResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\x12\x18\n" +
	"\aregions\x18\x02 \x03(\tR\aregions\"1\n" +
	"\x14GetVideoTrendRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\"F\n" +
	"\x15GetVideoTrendResponse\x12-\n" +
	"\x06points\x18\x01 \x03(\v2\x15.analytics.TrendPointR\x06points\"\xaa\x01\n" +
	"\n" +
	"TrendPoint\x129\n" +
	"\n" +
	"fetched_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tfetchedAt\x12\x1d\n" +
	"\n" +
	"view_count\x18\x02 \x01(\x03R\tviewCount\x12\x1d\n" +
	"\n" +
	"like_count\x18\x03 \x01(\x03R\tlikeCount\x12#\n" +
	"\rcomment_count\x18\x04 \x01(\x03R\fcommentCount*C\n" +
	"\x06SortBy\x12\x17\n" +
	"\x13SORT_BY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fAPPEAR_COUNT\x10\x01\x12\x0e\n" +
	"\n" +
	"VIEW_COUNT\x10\x022\xbc\x03\n" +
	"\x10AnalyticsService\x12F\n" +
	"\tGetVideos\x12\x1b.analytics.GetVideosRequest\x1a\x1c.analytics.GetVideosResponse\x12U\n" +
	"\x0eGetTopChannels\x12 .analytics.GetTopChannelsRequest\x1a!.analytics.GetTopChannelsResponse\x12U\n" +
	"\x0eGetVideosCount\x12 .analytics.GetVideosCountRequest\x1a!.analytics.GetVideosCountResponse\x12^\n" +
	"\x11GetTrackedRegions\x12#.analytics.GetTrackedRegionsRequest\x1a$.analytics.GetTrackedRegionsResponse\x12R\n" +
	"\rGetVideoTrend\x12\x1f.analytics.GetVideoTrendRequest\x1a .analytics.GetVideoTrendResponseB2Z0github.com/jacobhuynh/youtube-etl-pipeline/pb;pbb\x06proto3"

var (
	file_analytics_proto_rawDescOnce sync.Once
	file_analytics_proto_rawDescData []byte
)

func file_analytics_proto_rawDescGZIP() []byte {
	file_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)))
	})
	return file_analytics_proto_rawDescData
}

var file_analytics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_analytics_proto_goTypes = []any{
	(SortBy)(0),                       // 0: analytics.SortBy
	(*GetVideosRequest)(nil),          // 1: analytics.GetVideosRequest
	(*GetVideosResponse)(nil),         // 2: analytics.GetVideosResponse
	(*Video)(nil),                     // 3: analytics.Video
	(*GetTopChannelsRequest)(nil),     // 4: analytics.GetTopChannelsRequest
	(*GetTopChannelsResponse)(nil),    // 5: analytics.GetTopChannelsResponse
	(*Channel)(nil),                   // 6: analytics.Channel
	(*GetVideosCountRequest)(nil),     // 7: analytics.GetVideosCountRequest
	(*GetVideosCountResponse)(nil),    // 8: analytics.GetVideosCountResponse
	(*GetTrackedRegionsRequest)(nil),  // 9: analytics.GetTrackedRegionsRequest
	(*GetTrackedRegionsResponse)(nil), // 10: analytics.GetTrackedRegionsResponse
	(*GetVideoTrendRequest)(nil),      // 11: analytics.GetVideoTrendRequest
	(*GetVideoTrendResponse)(nil),     // 12: analytics.GetVideoTrendResponse
	(*TrendPoint)(nil),                // 13: analytics.TrendPoint
	(*timestamppb.Timestamp)(nil),     // 14: google.protobuf.Timestamp
}
var file_analytics_proto_depIdxs = []int32{
	14, // 0: analytics.GetVideosRequest.fetched_after:type_name -> google.protobuf.Timestamp
	14, // 1: analytics.GetVideosRequest.fetched_before:type_name -> google.protobuf.Timestamp
	3,  // 2: analytics.GetVideosResponse.videos:type_name -> analytics.Video
	14, // 3: analytics.Video.fetched_at:type_name -> google.protobuf.Timestamp
	14, // 4: analytics.Video.published_at:type_name -> google.protobuf.Timestamp
	0,  // 5: analytics.GetTopChannelsRequest.sort_by:type_name -> analytics.SortBy
	6,  // 6: analytics.GetTopChannelsResponse.channels:type_name -> analytics.Channel
	13, // 7: analytics.GetVideoTrendResponse.points:type_name -> analytics.TrendPoint
	14, // 8: analytics.TrendPoint.fetched_at:type_name -> google.protobuf.Timestamp
	1,  // 9: analytics.AnalyticsService.GetVideos:input_type -> analytics.GetVideosRequest
	4,  // 10: analytics.AnalyticsService.GetTopChannels:input_type -> analytics.GetTopChannelsRequest
	7,  // 11: analytics.AnalyticsService.GetVideosCount:input_type -> analytics.GetVideosCountRequest
	9,  // 12: analytics.AnalyticsService.GetTrackedRegions:input_type -> analytics.GetTrackedRegionsRequest
	11, // 13: analytics.AnalyticsService.GetVideoTrend:input_type -> analytics.GetVideoTrendRequest
	2,  // 14: analytics.AnalyticsService.GetVideos:output_type -> analytics.GetVideosResponse
	5,  // 15: analytics.AnalyticsService.GetTopChannels:output_type -> analytics.GetTopChannelsResponse
	8,  // 16: analytics.AnalyticsService.GetVideosCount:output_type -> analytics.GetVideosCountResponse
	10, // 17: analytics.AnalyticsService.GetTrackedRegions:output_type -> analytics.GetTrackedRegionsResponse
	12, // 18: analytics.AnalyticsService.GetVideoTrend:output_type -> analytics.GetVideoTrendResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_analytics_proto_init() }
func file_analytics_proto_init() {
	if File_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_proto_depIdxs,
		EnumInfos:         file_analytics_proto_enumTypes,
		MessageInfos:      file_analytics_proto_msgTypes,
	}.Build()
	File_analytics_proto = out.File
	file_analytics_proto_goTypes = nil
	file_analytics_proto_depIdxs = nil
}
