// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: etl.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobState int32

const (
	JobState_JOB_STATE_UNSPECIFIED JobState = 0
	JobState_JOB_STATE_DONE        JobState = 1
	JobState_JOB_STATE_FAILED      JobState = 2
	JobState_JOB_STATE_QUEUED      JobState = 3
	JobState_JOB_STATE_RUNNING     JobState = 4
	JobState_JOB_STATE_RETRYING    JobState = 5
	JobState_JOB_STATE_DEAD        JobState = 6
)

// Enum value maps for JobState.
var (
	JobState_name = map[int32]string{
		0: "JOB_STATE_UNSPECIFIED",
		1: "JOB_STATE_DONE",
		2: "JOB_STATE_FAILED",
		3: "JOB_STATE_QUEUED",
		4: "JOB_STATE_RUNNING",
		5: "JOB_STATE_RETRYING",
		6: "JOB_STATE_DEAD",
	}
	JobState_value = map[string]int32{
		"JOB_STATE_UNSPECIFIED": 0,
		"JOB_STATE_DONE":        1,
		"JOB_STATE_FAILED":      2,
		"JOB_STATE_QUEUED":      3,
		"JOB_STATE_RUNNING":     4,
		"JOB_STATE_RETRYING":    5,
		"JOB_STATE_DEAD":        6,
	}
)

func (x JobState) Enum() *JobState {
	p := new(JobState)
	*p = x
	return p
}

func (x JobState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobState) Descriptor() protoreflect.EnumDescriptor {
	return file_etl_proto_enumTypes[0].Descriptor()
}

func (JobState) Type() protoreflect.EnumType {
	return &file_etl_proto_enumTypes[0]
}

func (x JobState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobState.Descriptor instead.
func (JobState) EnumDescriptor() ([]byte, []int) {
	return file_etl_proto_rawDescGZIP(), []int{0}
}

type JobRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Region         string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	CategoryId     int32                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	MaxResults     int32                  `protobuf:"varint,3,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JobRequest) Reset() {
	*x = JobRequest{}
	mi := &file_etl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRequest) ProtoMessage() {}

func (x *JobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRequest.ProtoReflect.Descriptor instead.
func (*JobRequest) Descriptor() ([]byte, []int) {
	return file_etl_proto_rawDescGZIP(), []int{0}
}

func (x *JobRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *JobRequest) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *JobRequest) GetMaxResults() int32 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

func (x *JobRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *JobRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type JobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State         JobState               `protobuf:"varint,2,opt,name=state,proto3,enum=etl.JobState" json:"state,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResponse) Reset() {
	*x = JobResponse{}
	mi := &file_etl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResponse) ProtoMessage() {}

func (x *JobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_etl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResponse.ProtoReflect.Descriptor instead.
func (*JobResponse) Descriptor() ([]byte, []int) {
	return file_etl_proto_rawDescGZIP(), []int{1}
}

func (x *JobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobResponse) GetState() JobState {
	if x != nil {
		return x.State
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

func (x *JobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JobResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type JobStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State          JobState               `protobuf:"varint,2,opt,name=state,proto3,enum=etl.JobState" json:"state,omitempty"`
	Region         string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	CategoryId     int32                  `protobuf:"varint,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Attempt        int32                  `protobuf:"varint,5,opt,name=attempt,proto3" json:"attempt,omitempty"`
	MaxAttempts    int32                  `protobuf:"varint,6,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	VideosFetched  int32                  `protobuf:"varint,7,opt,name=videos_fetched,json=videosFetched,proto3" json:"videos_fetched,omitempty"`
	VideosInserted int32                  `protobuf:"varint,8,opt,name=videos_inserted,json=videosInserted,proto3" json:"videos_inserted,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	NextRetryAt    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=next_retry_at,json=nextRetryAt,proto3" json:"next_retry_at,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt    *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,14,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JobStatus) Reset() {
	*x = JobStatus{}
	mi := &file_etl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatus) ProtoMessage() {}

func (x *JobStatus) ProtoReflect() protoreflect.Message {
	mi := &file_etl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatus.ProtoReflect.Descriptor instead.
func (*JobStatus) Descriptor() ([]byte, []int) {
	return file_etl_proto_rawDescGZIP(), []int{2}
}

func (x *JobStatus) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobStatus) GetState() JobState {
	if x != nil {
		return x.State
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

func (x *JobStatus) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *JobStatus) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *JobStatus) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *JobStatus) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *JobStatus) GetVideosFetched() int32 {
	if x != nil {
		return x.VideosFetched
	}
	return 0
}

func (x *JobStatus) GetVideosInserted() int32 {
	if x != nil {
		return x.VideosInserted
	}
	return 0
}

func (x *JobStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *JobStatus) GetNextRetryAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRetryAt
	}
	return nil
}

func (x *JobStatus) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *JobStatus) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *JobStatus) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *JobStatus) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type JobUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State          JobState               `protobuf:"varint,2,opt,name=state,proto3,enum=etl.JobState" json:"state,omitempty"`
	VideosFetched  int32                  `protobuf:"varint,3,opt,name=videos_fetched,json=videosFetched,proto3" json:"videos_fetched,omitempty"`
	VideosInserted int32                  `protobuf:"varint,4,opt,name=videos_inserted,json=videosInserted,proto3" json:"videos_inserted,omitempty"`
	Message        string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JobUpdate) Reset() {
	*x = JobUpdate{}
	mi := &file_etl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobUpdate) ProtoMessage() {}

func (x *JobUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_etl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobUpdate.ProtoReflect.Descriptor instead.
func (*JobUpdate) Descriptor() ([]byte, []int) {
	return file_etl_proto_rawDescGZIP(), []int{3}
}

func (x *JobUpdate) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobUpdate) GetState() JobState {
	if x != nil {
		return x.State
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

func (x *JobUpdate) GetVideosFetched() int32 {
	if x != nil {
		return x.VideosFetched
	}
	return 0
}

func (x *JobUpdate) GetVideosInserted() int32 {
	if x != nil {
		return x.VideosInserted
	}
	return 0
}

func (x *JobUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JobUpdate) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

type BatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalReceived int32                  `protobuf:"varint,1,opt,name=total_received,json=totalReceived,proto3" json:"total_received,omitempty"`
	TotalAccepted int32                  `protobuf:"varint,2,opt,name=total_accepted,json=totalAccepted,proto3" json:"total_accepted,omitempty"`
	TotalRejected int32                  `protobuf:"varint,3,opt,name=total_rejected,json=totalRejected,proto3" json:"total_rejected,omitempty"`
	Results       []*BatchJobResult      `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchResponse) Reset() {
	*x = BatchResponse{}
	mi := &file_etl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResponse) ProtoMessage() {}

func (x *BatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_etl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResponse.ProtoReflect.Descriptor instead.
func (*BatchResponse) Descriptor() ([]byte, []int) {
	return file_etl_proto_rawDescGZIP(), []int{4}
}

func (x *BatchResponse) GetTotalReceived() int32 {
	if x != nil {
		return x.TotalReceived
	}
	return 0
}

func (x *BatchResponse) GetTotalAccepted() int32 {
	if x != nil {
		return x.TotalAccepted
	}
	return 0
}

func (x *BatchResponse) GetTotalRejected() int32 {
	if x != nil {
		return x.TotalRejected
	}
	return 0
}

func (x *BatchResponse) GetResults() []*BatchJobResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type BatchJobResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State          JobState               `protobuf:"varint,2,opt,name=state,proto3,enum=etl.JobState" json:"state,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Message        string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchJobResult) Reset() {
	*x = BatchJobResult{}
	mi := &file_etl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchJobResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchJobResult) ProtoMessage() {}

func (x *BatchJobResult) ProtoReflect() protoreflect.Message {
	mi := &file_etl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchJobResult.ProtoReflect.Descriptor instead.
func (*BatchJobResult) Descriptor() ([]byte, []int) {
	return file_etl_proto_rawDescGZIP(), []int{5}
}

func (x *BatchJobResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *BatchJobResult) GetState() JobState {
	if x != nil {
		return x.State
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

func (x *BatchJobResult) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *BatchJobResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetJobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusRequest) Reset() {
	*x = GetJobStatusRequest{}
	mi := &file_etl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusRequest) ProtoMessage() {}

func (x *GetJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusRequest.ProtoReflect.Descriptor instead.
func (*GetJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_etl_proto_rawDescGZIP(), []int{6}
}

func (x *GetJobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type WatchJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchJobRequest) Reset() {
	*x = WatchJobRequest{}
	mi := &file_etl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchJobRequest) ProtoMessage() {}

func (x *WatchJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchJobRequest.ProtoReflect.Descriptor instead.
func (*WatchJobRequest) Descriptor() ([]byte, []int) {
	return file_etl_proto_rawDescGZIP(), []int{7}
}

func (x *WatchJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

var File_etl_proto protoreflect.FileDescriptor

const file_etl_proto_rawDesc = "" +
	"\n" +
	"\tetl.proto\x12\x03etl\x1a\x1fgoogle/protobuf/timestamp.proto\"\x87\x02\n" +
	"\n" +
	"JobRequest\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x05R\n" +
	"categoryId\x12\x1f\n" +
	"\vmax_results\x18\x03 \x01(\x05R\n" +
	"maxResults\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x129\n" +
	"\bmetadata\x18\x05 \x03(\v2\x1d.etl.JobRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9e\x01\n" +
	"\vJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12#\n" +
	"\x05state\x18\x02 \x01(\x0e2\r.etl.JobStateR\x05state\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x9e\x05\n" +
	"\tJobStatus\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12#\n" +
	"\x05state\x18\x02 \x01(\x0e2\r.etl.JobStateR\x05state\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\x05R\n" +
	"categoryId\x12\x18\n" +
	"\aattempt\x18\x05 \x01(\x05R\aattempt\x12!\n" +
	"\fmax_attempts\x18\x06 \x01(\x05R\vmaxAttempts\x12%\n" +
	"\x0evideos_fetched\x18\a \x01(\x05R\rvideosFetched\x12'\n" +
	"\x0fvideos_inserted\x18\b \x01(\x05R\x0evideosInserted\x12#\n" +
	"\rerror_message\x18\t \x01(\tR\ferrorMessage\x12>\n" +
	"\rnext_retry_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vnextRetryAt\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x128\n" +
	"\bmetadata\x18\x0e \x03(\v2\x1c.etl.JobStatus.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xee\x01\n" +
	"\tJobUpdate\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12#\n" +
	"\x05state\x18\x02 \x01(\x0e2\r.etl.JobStateR\x05state\x12%\n" +
	"\x0evideos_fetched\x18\x03 \x01(\x05R\rvideosFetched\x12'\n" +
	"\x0fvideos_inserted\x18\x04 \x01(\x05R\x0evideosInserted\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12;\n" +
	"\voccurred_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\xb3\x01\n" +
	"\rBatchResponse\x12%\n" +
	"\x0etotal_received\x18\x01 \x01(\x05R\rtotalReceived\x12%\n" +
	"\x0etotal_accepted\x18\x02 \x01(\x05R\rtotalAccepted\x12%\n" +
	"\x0etotal_rejected\x18\x03 \x01(\x05R\rtotalRejected\x12-\n" +
	"\aresults\x18\x04 \x03(\v2\x13.etl.BatchJobResultR\aresults\"\x8f\x01\n" +
	"\x0eBatchJobResult\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12#\n" +
	"\x05state\x18\x02 \x01(\x0e2\r.etl.JobStateR\x05state\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\",\n" +
	"\x13GetJobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"(\n" +
	"\x0fWatchJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId*\xa8\x01\n" +
	"\bJobState\x12\x19\n" +
	"\x15JOB_STATE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eJOB_STATE_DONE\x10\x01\x12\x14\n" +
	"\x10JOB_STATE_FAILED\x10\x02\x12\x14\n" +
	"\x10JOB_STATE_QUEUED\x10\x03\x12\x15\n" +
	"\x11JOB_STATE_RUNNING\x10\x04\x12\x16\n" +
	"\x12JOB_STATE_RETRYING\x10\x05\x12\x12\n" +
	"\x0eJOB_STATE_DEAD\x10\x062\xe0\x01\n" +
	"\n" +
	"ETLService\x12.\n" +
	"\tSubmitJob\x12\x0f.etl.JobRequest\x1a\x10.etl.JobResponse\x124\n" +
	"\vSubmitBatch\x12\x0f.etl.JobRequest\x1a\x12.etl.BatchResponse(\x01\x128\n" +
	"\fGetJobStatus\x12\x18.etl.GetJobStatusRequest\x1a\x0e.etl.JobStatus\x122\n" +
	"\bWatchJob\x12\x14.etl.WatchJobRequest\x1a\x0e.etl.JobUpdate0\x01B2Z0github.com/jacobhuynh/youtube-etl-pipeline/pb;pbb\x06proto3"

var (
	file_etl_proto_rawDescOnce sync.Once
	file_etl_proto_rawDescData []byte
)

func file_etl_proto_rawDescGZIP() []byte {
	file_etl_proto_rawDescOnce.Do(func() {
		file_etl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_etl_proto_rawDesc), len(file_etl_proto_rawDesc)))
	})
	return file_etl_proto_rawDescData
}

var file_etl_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_etl_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_etl_proto_goTypes = []any{
	(JobState)(0),                 // 0: etl.JobState
	(*JobRequest)(nil),            // 1: etl.JobRequest
	(*JobResponse)(nil),           // 2: etl.JobResponse
	(*JobStatus)(nil),             // 3: etl.JobStatus
	(*JobUpdate)(nil),             // 4: etl.JobUpdate
	(*BatchResponse)(nil),         // 5: etl.BatchResponse
	(*BatchJobResult)(nil),        // 6: etl.BatchJobResult
	(*GetJobStatusRequest)(nil),   // 7: etl.GetJobStatusRequest
	(*WatchJobRequest)(nil),       // 8: etl.WatchJobRequest
	nil,                           // 9: etl.JobRequest.MetadataEntry
	nil,                           // 10: etl.JobStatus.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_etl_proto_depIdxs = []int32{
	9,  // 0: etl.JobRequest.metadata:type_name -> etl.JobRequest.MetadataEntry
	0,  // 1: etl.JobResponse.state:type_name -> etl.JobState
	11, // 2: etl.JobResponse.created_at:type_name -> google.protobuf.Timestamp
	0,  // 3: etl.JobStatus.state:type_name -> etl.JobState
	11, // 4: etl.JobStatus.next_retry_at:type_name -> google.protobuf.Timestamp
	11, // 5: etl.JobStatus.created_at:type_name -> google.protobuf.Timestamp
	11, // 6: etl.JobStatus.started_at:type_name -> google.protobuf.Timestamp
	11, // 7: etl.JobStatus.completed_at:type_name -> google.protobuf.Timestamp
	10, // 8: etl.JobStatus.metadata:type_name -> etl.JobStatus.MetadataEntry
	0,  // 9: etl.JobUpdate.state:type_name -> etl.JobState
	11, // 10: etl.JobUpdate.occurred_at:type_name -> google.protobuf.Timestamp
	6,  // 11: etl.BatchResponse.results:type_name -> etl.BatchJobResult
	0,  // 12: etl.BatchJobResult.state:type_name -> etl.JobState
	1,  // 13: etl.ETLService.SubmitJob:input_type -> etl.JobRequest
	1,  // 14: etl.ETLService.SubmitBatch:input_type -> etl.JobRequest
	7,  // 15: etl.ETLService.GetJobStatus:input_type -> etl.GetJobStatusRequest
	8,  // 16: etl.ETLService.WatchJob:input_type -> etl.WatchJobRequest
	2,  // 17: etl.ETLService.SubmitJob:output_type -> etl.JobResponse
	5,  // 18: etl.ETLService.SubmitBatch:output_type -> etl.BatchResponse
	3,  // 19: etl.ETLService.GetJobStatus:output_type -> etl.JobStatus
	4,  // 20: etl.ETLService.WatchJob:output_type -> etl.JobUpdate
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_etl_proto_init() }
func file_etl_proto_init() {
	if File_etl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_etl_proto_rawDesc), len(file_etl_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_etl_proto_goTypes,
		DependencyIndexes: file_etl_proto_depIdxs,
		EnumInfos:         file_etl_proto_enumTypes,
		MessageInfos:      file_etl_proto_msgTypes,
	}.Build()
	File_etl_proto = out.File
	file_etl_proto_goTypes = nil
	file_etl_proto_depIdxs = nil
}
