// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: etl.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ETLService_SubmitJob_FullMethodName    = "/etl.ETLService/SubmitJob"
	ETLService_SubmitBatch_FullMethodName  = "/etl.ETLService/SubmitBatch"
	ETLService_GetJobStatus_FullMethodName = "/etl.ETLService/GetJobStatus"
	ETLService_WatchJob_FullMethodName     = "/etl.ETLService/WatchJob"
)

// ETLServiceClient is the client API for ETLService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ETLServiceClient interface {
	SubmitJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*JobResponse, error)
	SubmitBatch(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[JobRequest, BatchResponse], error)
	GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*JobStatus, error)
	WatchJob(ctx context.Context, in *WatchJobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobUpdate], error)
}

type eTLServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewETLServiceClient(cc grpc.ClientConnInterface) ETLServiceClient {
	return &eTLServiceClient{cc}
}

func (c *eTLServiceClient) SubmitJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*JobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobResponse)
	err := c.cc.Invoke(ctx, ETLService_SubmitJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eTLServiceClient) SubmitBatch(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[JobRequest, BatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ETLService_ServiceDesc.Streams[0], ETLService_SubmitBatch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[JobRequest, BatchResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ETLService_SubmitBatchClient = grpc.ClientStreamingClient[JobRequest, BatchResponse]

func (c *eTLServiceClient) GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*JobStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobStatus)
	err := c.cc.Invoke(ctx, ETLService_GetJobStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eTLServiceClient) WatchJob(ctx context.Context, in *WatchJobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ETLService_ServiceDesc.Streams[1], ETLService_WatchJob_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchJobRequest, JobUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ETLService_WatchJobClient = grpc.ServerStreamingClient[JobUpdate]

// ETLServiceServer is the server API for ETLService service.
// All implementations must embed UnimplementedETLServiceServer
// for forward compatibility.
type ETLServiceServer interface {
	SubmitJob(context.Context, *JobRequest) (*JobResponse, error)
	SubmitBatch(grpc.ClientStreamingServer[JobRequest, BatchResponse]) error
	GetJobStatus(context.Context, *GetJobStatusRequest) (*JobStatus, error)
	WatchJob(*WatchJobRequest, grpc.ServerStreamingServer[JobUpdate]) error
	mustEmbedUnimplementedETLServiceServer()
}

// UnimplementedETLServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedETLServiceServer struct{}

func (UnimplementedETLServiceServer) SubmitJob(context.Context, *JobRequest) (*JobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitJob not implemented")
}
func (UnimplementedETLServiceServer) SubmitBatch(grpc.ClientStreamingServer[JobRequest, BatchResponse]) error {
	return status.Error(codes.Unimplemented, "method SubmitBatch not implemented")
}
func (UnimplementedETLServiceServer) GetJobStatus(context.Context, *GetJobStatusRequest) (*JobStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJobStatus not implemented")
}
func (UnimplementedETLServiceServer) WatchJob(*WatchJobRequest, grpc.ServerStreamingServer[JobUpdate]) error {
	return status.Error(codes.Unimplemented, "method WatchJob not implemented")
}
func (UnimplementedETLServiceServer) mustEmbedUnimplementedETLServiceServer() {}
func (UnimplementedETLServiceServer) testEmbeddedByValue()                    {}

// UnsafeETLServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ETLServiceServer will
// result in compilation errors.
type UnsafeETLServiceServer interface {
	mustEmbedUnimplementedETLServiceServer()
}

func RegisterETLServiceServer(s grpc.ServiceRegistrar, srv ETLServiceServer) {
	// If the following call panics, it indicates UnimplementedETLServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ETLService_ServiceDesc, srv)
}

func _ETLService_SubmitJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ETLServiceServer).SubmitJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ETLService_SubmitJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ETLServiceServer).SubmitJob(ctx, req.(*JobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ETLService_SubmitBatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ETLServiceServer).SubmitBatch(&grpc.GenericServerStream[JobRequest, BatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ETLService_SubmitBatchServer = grpc.ClientStreamingServer[JobRequest, BatchResponse]

func _ETLService_GetJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ETLServiceServer).GetJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ETLService_GetJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ETLServiceServer).GetJobStatus(ctx, req.(*GetJobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ETLService_WatchJob_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchJobRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ETLServiceServer).WatchJob(m, &grpc.GenericServerStream[WatchJobRequest, JobUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ETLService_WatchJobServer = grpc.ServerStreamingServer[JobUpdate]

// ETLService_ServiceDesc is the grpc.ServiceDesc for ETLService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ETLService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "etl.ETLService",
	HandlerType: (*ETLServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitJob",
			Handler:    _ETLService_SubmitJob_Handler,
		},
		{
			MethodName: "GetJobStatus",
			Handler:    _ETLService_GetJobStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubmitBatch",
			Handler:       _ETLService_SubmitBatch_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "WatchJob",
			Handler:       _ETLService_WatchJob_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "etl.proto",
}
